### ISSUE TITLE
Add more resources for Git and GitHub section

### ISSUE THREAD

**Issue by Greeshma2903** [arpit456jain/Web-Development-Path-And-Resources#18]
Can I add few more resources to the **Git and Github** section like
- documentation version
- Learn git branching?

**Comment by arpit456jain** [comment]
Sure why not @Greeshma2903 
Go ahead and thanks in advance

**Comment by Greeshma2903** [comment]
Thank you!

**Comment by arpit456jain** [comment]
@Greeshma2903 must check the repos mentioned in important repos front end related

They are really awesome repos

And the repo for dsa path also mention in last

**Comment by Greeshma2903** [comment]
> @Greeshma2903 must check the repos mentioned in important repos front end related
> 
> They are really awesome repos
> 
> And the repo for dsa path also mention in last

Yess indeed! These are some really good resources😀
