### ISSUE TITLE
README Update : Nonexistent url in Django Projects ( ToDoList )

### ISSUE THREAD

**Issue by kaustav202** [arpit456jain/Web-Development-Path-And-Resources#27]
The repository linked to by To DoList under Django Projects does not exist.

Can i be assigned the task of fixing this to correct url?

I'm gssoc22 contributor

**Comment by arpit456jain** [comment]
This project is not under GSSoC'22
@kaustav202

**Comment by kaustav202** [comment]
Oh my bad .. had this repo stared from earlier so didn't notice.
I hope you make the change anyway : )

**Comment by arpit456jain** [comment]
yeah thanks for pointing it out
